name: Printer
main: com.reliableplugins.printer.Printer
version: 1.3
depend: [Vault, Factions]
softdepend: [SuperiorSkyblock2, ShopGuiPlus]
author: Reachy
commands:
  printer:
    description: Help command for Printer
    usage: "/printer help"