name: Printer
main: com.reliableplugins.printer.Printer
version: 1.9.1
depend:
  - Vault
softdepend:
  - Citizens
  - SuperiorSkyblock2
  - ShopGUIPlus
  - zShop
  - Residence
  - Factions
author: Reachy
commands:
  printer:
    description: Help command for Printer
    usage: "/printer help"