name: Printer
main: com.reliableplugins.printer.Printer
version: 1.3
depend: [Vault]
softdepend:
  - SuperiorSkyblock2
  - Factions
  - ShopGuiPlus
author: Reachy
commands:
  printer:
    description: Help command for Printer
    usage: "/printer help"