name: Printer
main: com.reliableplugins.printer.Printer
version: 1.7
depend:
  - Vault
softdepend:
  - SuperiorSkyblock2
  - ShopGUIPlus
  - Factions
author: Reachy
commands:
  printer:
    description: Help command for Printer
    usage: "/printer help"